### PR TITLE
Log execution-id in addition to command-id in the SDK

### PR DESCRIPTION
**Pull request by gkousik**
This is to be consistent with remote execution clients.

### CODE REVIEW

**Review by atetubou — APPROVED** [review]

**Review by ramymedhat — COMMENTED** [review]
Can we query gws logs with the execution ID?

**Comment by gkousik** [comment]
Nope I don't think so. You could go from execution-id -> command-id (from reproxy_log), then query on command-id. I think that's ok because GWS logs can't be queried immediately anyway (there's a 10-15m delay) and by that time, you can probably lookup reproxy_log.

Alternatively I could modify this to log both command and execution-id. These are V(1) logs anyway, so doesn't hurt to log both.

**Comment by ola-rozenfeld** [comment]
Maybe log the command ID on every line, and execution ID somewhere once in the beginning of a function. There are a couple of differences between them -- command id is stable; command id is much shorter. Logging both will be a lot less readable, imo.

**Comment by gkousik** [comment]
Logged both command-id and execution-id as we discussed offline.

**Review by ramymedhat — APPROVED** [review]
Thanks! Very timely :)

**Pull request merged**
