### PR TITLE
Make CI run multiple tests.

### PR DESCRIPTION
**Pull request by rubensf**
While this has a toil on CI performance, this project is still small
enough that this is cost is easily affordable.

### CODE REVIEW

**Review by ola-rozenfeld — COMMENTED** [review]
Just curious, how long does it take with this change vs without?

**Comment by rubensf** [comment]
~1min without these changes.
I tried with [runs_per_test=5](https://buildkite.com/bazel/remote-apis-sdks/builds/1292) and it goes to ~4.5 minutes, [=10](https://buildkite.com/bazel/remote-apis-sdks/builds/1290) to ~8-9minutes, but the 5 runs per test didn't reliably catch the concurrency issue we're experiencing.

In any case, we can run these tests locally much faster without checking for eg concurrency, so I don't believe the extra time to be problematic.

**Comment by ifoox** [comment]
Would it be useful to set this up as a parallel target (like the gobuild one below) so that you could get fast results without the race detector, and then get results with it after 10 mins?

**Comment by rubensf** [comment]
I'm not opposed to the idea if y'all think it useful, but I think the *real* faster way is just running `bazel test ...` or `go test ./...` which saves even more time, before pushing it to github. I think of these more as "sanity checks".

**Comment by ola-rozenfeld** [comment]
I agree with Igor. I find the go formatter here to be more useful than in my client (it catches errors such as forgetting the right amount of parameters in fmt.Printf); also, some external developers might forget to run the tests, or run them via go and not bazel which might cause some differences. Also, the presubmits are for various platforms (or should be...).
So, overall, I often find that the presubmit helps a lot, and the faster it is (or parts of it), the better.

**Comment by rubensf** [comment]
Sounds good - done.

**Review by ola-rozenfeld — APPROVED** [review]

**Comment by gkousik** [comment]
Did the race test succeed locally for you? Is it only failing on buildkite?

**Comment by ola-rozenfeld** [comment]
Oh, it's supposed to fail, until I fix my bug. This is WAI.

**Review by ola-rozenfeld — COMMENTED** [review]
Suggestion: split them further with:

```
  # Deflake with multiple runs per test.
  ubuntu1804_deflake:
    platform: ubuntu1804
    name: "bazel deflake check"
    test_flags:
    - "--runs_per_test=100"
    test_targets:
    - "//..."
  # Check that gorace succeeds.
  ubuntu1804_race:
    platform: ubuntu1804
    name: "bazel race check"
    test_flags:
    - "--features=race"
    test_targets:
    - "//..."
```

This is what I used for testing #256. It currently doesn't work because TestCompressedReads fails racing, but it will be faster once #256 is in.

**Comment by ola-rozenfeld** [comment]
I think if you rebase now and use my suggestion, it should pass now.

**Pull request closed without merging**
